mesosMaster: 10.0.2.15:5050
checkpoint: false
frameworkFailoverTimeout: 43200000
frameworkName: MyriadAlpha
frameworkRole: 
frameworkUser: hduser     # User the Node Manager runs as, required if nodeManagerURI set, otherwise defaults to the user
                          # running the resource manager.
frameworkSuperUser: root  # To be depricated, currently permissions need set by a superuser due to Mesos-1790.  Must be
                          # root or have passwordless sudo. Required if nodeManagerURI set, ignored otherwise.
nativeLibrary: /usr/local/lib/libmesos.so
zkServers: localhost:2181
zkTimeout: 20000
restApiPort: 8192
profiles:
  small:
    cpu: 1
    mem: 1100
  medium:
    cpu: 2
    mem: 2048
  large:
    cpu: 4
    mem: 4096
rebalancer: false
nodemanager:
  jvmMaxMemoryMB: 1024
  cpus: 0.2
  cgroups: false
executor:
  jvmMaxMemoryMB: 256
  path: file:///usr/local/libexec/mesos/myriad-executor-runnable-0.0.1.jar
  #The following should be used for a remotely distributed URI, hdfs assumed but other URI types valid.
  #nodeManagerUri: hdfs://namenode:port/dist/hadoop-2.5.0.tar.gz
  #path: hdfs://namenode:port/dist/myriad-executor-runnable-0.0.1.jar
yarnEnvironment:
  YARN_HOME: /usr/local/hadoop
  #YARN_HOME: hadoop-2.5.0 #this should be relative if nodeManagerUri is set
  #JAVA_HOME: /usr/lib/jvm/java-default #System dependent, but sometimes necessary
mesosAuthenticationPrincipal:
mesosAuthenticationSecretFilename:
